-- Funny responses
CREATE TABLE IF NOT EXISTS funny_responses (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    response TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO funny_responses (response) VALUES
('ACCESS DENIED'),
('FORBIDDEN'),
('DENIED'),
('NOT ALLOWED'),
('NO!'),
('NO WAY'),
('You shall not pass'),
('You are not allowed to do that'),
('Stop right there'),
('You are not the boss of me'),
('You can''t do that'),
('Stop it!'),
('That''s not how it works'),
('It starts to hurt'),
('I WILL NOT ALLOW IT'),
('Please give up'),
('Theres no more unique responses, please stop'),
('I''m for real, that''s the last one'),
('ACCESS DENIED'),
('ACCESS DENIED'),
('ACCESS DENIED'),
('ACCESS DENIED, ACCESS DENIED'),
('ACCESS DENIED, ACCESS DENIED, ACCESS DENIED'),
('It will not work, I promise'),
('You are not allowed to do that'),
('You are not allowed to do that, I promise'),
('You command executed successfully, but I lost the out'),
('SUCCESS'),
('MORE SUCCESS'),
('SUCCESS, SUCCESS, SUCCESS'),
('YOU COMPLETED THE QUEST, CONGRATULATIONS'),
('YOU ARE THE CHOSEN ONE'),
('YOU ARE THE ONE'),
('YOU ARE THE ONE, THE ONLY ONE'),
('You gained 150 XP'),
('You lost the XP'),
('You gained 150 XP, but lost 200'),
('Thats the end.'),
('The End'),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
('');

